title: HATCX - Linking humans to their health
email: contact@HATCX.com
description: > # this means to ignore newlines until "baseurl:"
  HATCX is an Omaha, NE  based technology solutions company, focusing on healthcare
baseurl: "" # the subpath of your site, e.g. /blog
url: "hatcx.com" # the base hostname & protocol for your site
facebook: 'https://www.facebook.com/hatcxhealth/'
twitter: 'https://twitter.com/HATCX_'

# Build settings
markdown: kramdown
# repository: PAGES_REPO_NWO
sass:
  style: compressed
# Plugins
gems:
  - jekyll-sitemap
