# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HATCX - Linking humans to their health
email: contact@HATCX.com
description: > # this means to ignore newlines until "baseurl:"
  HATCX is an Omaha, NE technology solutions company, focusing on healthcare
baseurl: "" # the subpath of your site, e.g. /blog
url: "hatcx.com" # the base hostname & protocol for your site
facebook: 'https://www.facebook.com/hatcxhealth/'
twitter: 'https://twitter.com/HATCX_'

# Build settings
markdown: kramdown
repository: PAGES_REPO_NWO
sass:
  style: compressed
# Plugins
gems:
  - jekyll-sitemap
